#!/usr/bin/python

DOMAIN = "mintupload"
PATH = "/usr/share/linuxmint/locale"

import os, gettext, sys
sys.path.append('/usr/lib/linuxmint/common')
import additionalfiles

os.environ['LANG'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=mintupload-manager
Icon=/usr/lib/linuxmint/mintUpload/icon.svg
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
StartupNotify=false
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/upload-manager.desktop", prefix, _("Upload Manager"), _("Define upload services"), suffix)
