#!/bin/bash

xgettext --language=Python --keyword=_ --output=mintupload.pot usr/lib/linuxmint/mintUpload/mintUpload.py usr/lib/linuxmint/mintUpload/mintUploadCore.py usr/lib/linuxmint/mintUpload/file-uploader.py usr/lib/linuxmint/mintUpload/upload-manager.py generate_desktop_files
