#!/bin/bash

xgettext --language=Python --keyword=_ --output=mintupload.pot usr/lib/linuxmint/mintupload/mintUpload.py usr/lib/linuxmint/mintupload/mintUploadCore.py usr/lib/linuxmint/mintupload/file-uploader.py usr/lib/linuxmint/mintupload/upload-manager.py generate_desktop_files
