#!/bin/sh

xgettext --language=Python --keyword=_ --output=mintupload.pot usr/share/linuxmint/mintUpload/mintUpload.py usr/share/linuxmint/mintUpload/mintUploadCore.py usr/share/linuxmint/mintUpload/file-uploader.py usr/share/linuxmint/mintUpload/upload-manager.py generate_desktop_files
